// GENERATED by seed/import-team.ts - do not edit by hand.
// 42 people across 15 teams, from 55 photographs.
//
// Identity was resolved by comparing the photographs, not the names. Every repeated name is one
// person photographed once and cropped differently, with two exceptions: "Rezwan" in Tech
// Vanguard is "Rezwanul Huda" from Management, and "Tonmoy" is two different people, told apart
// here as "Tonmoy (IQVIA)" and "Tonmoy (Playaz4Playaz)".
//
// Role titles come from the export where it states one, and otherwise from the team. Skills are
// one per team, held at 3 out of 5 by its members: the export carries no proficiency data, and
// inventing differences between named colleagues would be fabricating it.

export interface TeamPerson {
  name: string;
  slug: string;
  roleTitle: string;
  avatarUrl: string | null;
}

export interface TeamProject {
  name: string;
  status: 'PLANNED' | 'ACTIVE' | 'ON_HOLD' | 'COMPLETED' | 'CANCELLED';
  role: string;
  skill: string;
  members: Array<{ slug: string; role: string }>;
}

export const PEOPLE: TeamPerson[] = [
  {
    name: 'Abdullah',
    slug: 'abdullah',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/abdullah.jpg',
  },
  {
    name: 'Abrar',
    slug: 'abrar',
    roleTitle: 'AppDevOps Engineer',
    avatarUrl: '/avatars/abrar.jpg',
  },
  {
    name: 'Asif (NybSys)',
    slug: 'asif-nybsys',
    roleTitle: 'Site Reliability Engineer',
    avatarUrl: '/avatars/asif-nybsys.jpg',
  },
  {
    name: 'Baset',
    slug: 'baset',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/baset.jpg',
  },
  {
    name: 'Eduard',
    slug: 'eduard',
    roleTitle: 'Software Engineer',
    avatarUrl: null,
  },
  {
    name: 'Faysal',
    slug: 'faysal',
    roleTitle: 'AppDevOps Engineer',
    avatarUrl: '/avatars/faysal.jpg',
  },
  {
    name: 'Gabinda',
    slug: 'gabinda',
    roleTitle: 'Site Reliability Engineer',
    avatarUrl: '/avatars/gabinda.jpg',
  },
  {
    name: 'Hasin',
    slug: 'hasin',
    roleTitle: 'Committee Member',
    avatarUrl: '/avatars/hasin.jpg',
  },
  {
    name: 'Ibnul',
    slug: 'ibnul',
    roleTitle: 'Data Engineer',
    avatarUrl: '/avatars/ibnul.jpg',
  },
  {
    name: 'Ibrahim',
    slug: 'ibrahim',
    roleTitle: 'Office Administrator',
    avatarUrl: '/avatars/ibrahim.jpg',
  },
  {
    name: 'Ishraque',
    slug: 'ishraque',
    roleTitle: 'AppDevOps Engineer',
    avatarUrl: '/avatars/ishraque.jpg',
  },
  {
    name: 'Ismith',
    slug: 'ismith',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/ismith.jpg',
  },
  {
    name: 'Joy',
    slug: 'joy',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/joy.jpg',
  },
  {
    name: 'Lushan',
    slug: 'lushan',
    roleTitle: 'People & Culture Specialist',
    avatarUrl: '/avatars/lushan.jpg',
  },
  {
    name: 'Mahabub',
    slug: 'mahabub',
    roleTitle: 'Tech Lead',
    avatarUrl: '/avatars/mahabub.jpg',
  },
  {
    name: 'Mahdi',
    slug: 'mahdi',
    roleTitle: 'Site Reliability Engineer',
    avatarUrl: '/avatars/mahdi.jpg',
  },
  {
    name: 'Mahfuzul',
    slug: 'mahfuzul',
    roleTitle: 'AVP',
    avatarUrl: '/avatars/mahfuzul.jpg',
  },
  {
    name: 'Nahid',
    slug: 'nahid',
    roleTitle: 'Data Engineer',
    avatarUrl: '/avatars/nahid.jpg',
  },
  {
    name: 'Nazia Islam',
    slug: 'nazia-islam',
    roleTitle: 'Chairman',
    avatarUrl: '/avatars/nazia-islam.jpg',
  },
  {
    name: 'Odree',
    slug: 'odree',
    roleTitle: 'KPI Analyst',
    avatarUrl: '/avatars/odree.jpg',
  },
  {
    name: 'Raiyan',
    slug: 'raiyan',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/raiyan.jpg',
  },
  {
    name: 'Rashad',
    slug: 'rashad',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/rashad.jpg',
  },
  {
    name: 'Reza',
    slug: 'reza',
    roleTitle: 'Site Reliability Engineer',
    avatarUrl: '/avatars/reza.jpg',
  },
  {
    name: 'Rezwanul Huda',
    slug: 'rezwanul-huda',
    roleTitle: 'CEO',
    avatarUrl: '/avatars/rezwanul-huda.jpg',
  },
  {
    name: 'Rubel',
    slug: 'rubel',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/rubel.jpg',
  },
  {
    name: 'Sabbir',
    slug: 'sabbir',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/sabbir.jpg',
  },
  {
    name: 'Saqlain',
    slug: 'saqlain',
    roleTitle: 'Accountant',
    avatarUrl: '/avatars/saqlain.jpg',
  },
  {
    name: 'Sazzad',
    slug: 'sazzad',
    roleTitle: 'Site Reliability Engineer',
    avatarUrl: '/avatars/sazzad.jpg',
  },
  {
    name: 'Shahir',
    slug: 'shahir',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/shahir.jpg',
  },
  {
    name: 'Shalin',
    slug: 'shalin',
    roleTitle: 'Tech Lead',
    avatarUrl: '/avatars/shalin.jpg',
  },
  {
    name: 'Shams',
    slug: 'shams',
    roleTitle: 'SVP',
    avatarUrl: '/avatars/shams.jpg',
  },
  {
    name: 'Shaon',
    slug: 'shaon',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/shaon.jpg',
  },
  {
    name: 'Shifat',
    slug: 'shifat',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/shifat.jpg',
  },
  {
    name: 'Shohag',
    slug: 'shohag',
    roleTitle: 'Office Administrator',
    avatarUrl: '/avatars/shohag.jpg',
  },
  {
    name: 'Shohan',
    slug: 'shohan',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/shohan.jpg',
  },
  {
    name: 'Sohel',
    slug: 'sohel',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/sohel.jpg',
  },
  {
    name: 'Tayabur',
    slug: 'tayabur',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/tayabur.jpg',
  },
  {
    name: 'Tofayel',
    slug: 'tofayel',
    roleTitle: 'Data Engineer',
    avatarUrl: '/avatars/tofayel.jpg',
  },
  {
    name: 'Tonmoy (IQVIA)',
    slug: 'tonmoy-iqvia',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/tonmoy-iqvia.jpg',
  },
  {
    name: 'Tonmoy (Playaz4Playaz)',
    slug: 'tonmoy-playaz4playaz',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/tonmoy-playaz4playaz.jpg',
  },
  {
    name: 'Yeasir',
    slug: 'yeasir',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/yeasir.jpg',
  },
  {
    name: 'Zakaria',
    slug: 'zakaria',
    roleTitle: 'Software Engineer',
    avatarUrl: '/avatars/zakaria.jpg',
  },
];

export const TEAM_PROJECTS: TeamProject[] = [
  {
    name: 'Data Warehouse',
    status: 'ACTIVE',
    role: 'Data Engineer',
    skill: 'Data Warehousing',
    members: [
      {
        slug: 'ibnul',
        role: 'Data Engineer',
      },
      {
        slug: 'nahid',
        role: 'Data Engineer',
      },
      {
        slug: 'shalin',
        role: 'Data Engineer',
      },
      {
        slug: 'shohan',
        role: 'Data Engineer',
      },
      {
        slug: 'tofayel',
        role: 'Data Engineer',
      },
    ],
  },
  {
    name: 'People & Culture',
    status: 'ACTIVE',
    role: 'People & Culture Specialist',
    skill: 'People Operations',
    members: [
      {
        slug: 'lushan',
        role: 'People & Culture Specialist',
      },
    ],
  },
  {
    name: 'Accounts',
    status: 'ACTIVE',
    role: 'Accountant',
    skill: 'Accounting',
    members: [
      {
        slug: 'saqlain',
        role: 'Accountant',
      },
    ],
  },
  {
    name: 'Office Administration',
    status: 'ACTIVE',
    role: 'Office Administrator',
    skill: 'Office Administration',
    members: [
      {
        slug: 'ibrahim',
        role: 'Office Administrator',
      },
      {
        slug: 'shohag',
        role: 'Office Administrator',
      },
    ],
  },
  {
    name: 'Minsk Team Member',
    status: 'ACTIVE',
    role: 'Software Engineer',
    skill: 'Application Development',
    members: [
      {
        slug: 'eduard',
        role: 'Software Engineer',
      },
    ],
  },
  {
    name: 'Committees - Tech Vanguard',
    status: 'ACTIVE',
    role: 'Committee Member',
    skill: 'Technical Governance',
    members: [
      {
        slug: 'mahabub',
        role: 'Tech Lead',
      },
      {
        slug: 'mahfuzul',
        role: 'AVP',
      },
      {
        slug: 'rezwanul-huda',
        role: 'CEO',
      },
      {
        slug: 'shalin',
        role: 'Tech Lead',
      },
      {
        slug: 'shams',
        role: 'SVP',
      },
    ],
  },
  {
    name: 'Committees - Tech Committee',
    status: 'ACTIVE',
    role: 'Committee Member',
    skill: 'Technical Governance',
    members: [
      {
        slug: 'baset',
        role: 'Committee Member',
      },
      {
        slug: 'hasin',
        role: 'Committee Member',
      },
      {
        slug: 'mahdi',
        role: 'Committee Member',
      },
      {
        slug: 'sabbir',
        role: 'Committee Member',
      },
      {
        slug: 'tayabur',
        role: 'Committee Member',
      },
      {
        slug: 'tonmoy-iqvia',
        role: 'Committee Member',
      },
    ],
  },
  {
    name: 'Management',
    status: 'ACTIVE',
    role: 'Executive',
    skill: 'Leadership',
    members: [
      {
        slug: 'nazia-islam',
        role: 'Chairman',
      },
      {
        slug: 'rezwanul-huda',
        role: 'CEO',
      },
    ],
  },
  {
    name: 'IQVIA AppDevOps @ Agentic AI',
    status: 'ACTIVE',
    role: 'AppDevOps Engineer',
    skill: 'Agentic AI',
    members: [
      {
        slug: 'abrar',
        role: 'AppDevOps Engineer',
      },
      {
        slug: 'faysal',
        role: 'AppDevOps Engineer',
      },
      {
        slug: 'ishraque',
        role: 'AppDevOps Engineer',
      },
      {
        slug: 'shams',
        role: 'AppDevOps Engineer',
      },
    ],
  },
  {
    name: 'SRE (IQVIA)',
    status: 'ACTIVE',
    role: 'Site Reliability Engineer',
    skill: 'Site Reliability',
    members: [
      {
        slug: 'asif-nybsys',
        role: 'Site Reliability Engineer',
      },
      {
        slug: 'gabinda',
        role: 'Site Reliability Engineer',
      },
      {
        slug: 'mahdi',
        role: 'Site Reliability Engineer',
      },
      {
        slug: 'reza',
        role: 'Site Reliability Engineer',
      },
      {
        slug: 'sazzad',
        role: 'Site Reliability Engineer',
      },
    ],
  },
  {
    name: 'KPI (IQVIA)',
    status: 'ACTIVE',
    role: 'KPI Analyst',
    skill: 'Reporting',
    members: [
      {
        slug: 'mahabub',
        role: 'KPI Analyst',
      },
      {
        slug: 'odree',
        role: 'KPI Analyst',
      },
    ],
  },
  {
    name: 'IQVIA PH',
    status: 'ACTIVE',
    role: 'Software Engineer',
    skill: 'Application Development',
    members: [
      {
        slug: 'baset',
        role: 'Software Engineer',
      },
      {
        slug: 'tonmoy-iqvia',
        role: 'Software Engineer',
      },
    ],
  },
  {
    name: 'Playaz4Playaz',
    status: 'ACTIVE',
    role: 'Software Engineer',
    skill: 'Application Development',
    members: [
      {
        slug: 'joy',
        role: 'Software Engineer',
      },
      {
        slug: 'rubel',
        role: 'Software Engineer',
      },
      {
        slug: 'shifat',
        role: 'Software Engineer',
      },
      {
        slug: 'tayabur',
        role: 'Software Engineer',
      },
      {
        slug: 'tonmoy-playaz4playaz',
        role: 'Software Engineer',
      },
    ],
  },
  {
    name: 'Ajentica Panopto',
    status: 'ACTIVE',
    role: 'Software Engineer',
    skill: 'Panopto Platform',
    members: [
      {
        slug: 'ismith',
        role: 'Software Engineer',
      },
      {
        slug: 'raiyan',
        role: 'Software Engineer',
      },
      {
        slug: 'rashad',
        role: 'Software Engineer',
      },
      {
        slug: 'rubel',
        role: 'Software Engineer',
      },
      {
        slug: 'sabbir',
        role: 'Software Engineer',
      },
      {
        slug: 'shaon',
        role: 'Software Engineer',
      },
      {
        slug: 'yeasir',
        role: 'Software Engineer',
      },
      {
        slug: 'zakaria',
        role: 'Software Engineer',
      },
    ],
  },
  {
    name: 'Ajentica Lumistry',
    status: 'ACTIVE',
    role: 'Software Engineer',
    skill: 'Lumistry Platform',
    members: [
      {
        slug: 'abdullah',
        role: 'Software Engineer',
      },
      {
        slug: 'mahfuzul',
        role: 'Software Engineer',
      },
      {
        slug: 'rubel',
        role: 'Software Engineer',
      },
      {
        slug: 'shahir',
        role: 'Software Engineer',
      },
      {
        slug: 'shohan',
        role: 'Software Engineer',
      },
      {
        slug: 'sohel',
        role: 'Software Engineer',
      },
    ],
  },
];
